services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  fastify:
    container_name: fastify
    image: custom-fastify
    build:
      context: ./Backend
      dockerfile: Fastify/Dockerfile
    ports:
      - "3000:3000"
      - "3443:3443"
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL="redis://redis:6379"
      - VAULT_ADDR=https://vault:8200
    depends_on:
      vault:
        condition: service_started
      redis:
        condition: service_started
    command: sh -c "echo 'Waiting for Vault...' && sleep 20 && echo 'Starting Fastify...' && npm start"
    volumes:
      - ./Backend/Fastify:/app
      - /app/node_modules
      - ./Data/vault_data:/app/vault/data
      - ./Data/sqlite_data:/app/Data/db
      - ./Data/uploads:/usr/share/nginx/uploads
      - ./Security/Nginx/ssl:/etc/fastify/ssl

  nginx:
    container_name: nginx
    build:
      context: ./Security
      dockerfile: Nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8143:8143"
      - "8444:8444"
    depends_on:
      - fastify
      - tsengine
      - vault
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=off
    volumes:
      - ./Security/Nginx/conf.d:/etc/nginx/conf.d
      - ./Security/Nginx/passwd:/etc/nginx/passwd
      - ./Security/Nginx/ssl:/etc/nginx/ssl
      - ./Security/ModSecurity:/etc/modsecurity
      - ./Frontend/public:/usr/share/nginx/html:ro
      - ./Frontend/public/srcs:/usr/share/nginx/dist/srcs:ro 
      - ./Frontend/public/static/js/css:/usr/share/nginx/dist/static/js/css:ro
      - ./Frontend/public/index.html:/usr/share/nginx/dist/index.html:ro
      - ./Frontend/dist:/usr/share/nginx/dist
      - ./Frontend/dist/api:/usr/share/nginx/dist/api:ro
      - ./Frontend/admin:/usr/share/nginx/admin:ro
      - ./Data/uploads:/usr/share/nginx/uploads

  tsengine:
    image: node:20-alpine
    container_name: tsengine
    working_dir: /app
    environment:
    - TZ=Europe/Paris
    command: >
      sh -c "apk add --no-cache tzdata &&
              npm i -g typescript && npm i &&
              mkdir -p /app/dist &&
              tsc --project /app/tsconfig.json --watch"
    volumes:
      - ./Frontend/public:/app/public
      - ./Frontend/dist:/app/dist
      - ./Frontend/package.json:/app/package.json
      - ./Frontend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    restart: unless-stopped

  vault:
    image: custom-vault
    container_name: vault
    restart: always
    build:
      context: ./Security/Vault
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    env_file:
      - .env
    environment:
      - VAULT_ADDR=https://127.0.0.1:8200
    volumes:
      - ./Data/vault_data:/vault/data
      - ./Security/Vault/scripts:/vault/scripts
      - ./Security/Nginx/passwd:/nginx/passwd
      - ./Security/Nginx/ssl:/vault/ssl
    cap_add:
      - IPC_LOCK

# networks:
#   transcendence-network:
#      driver: bridge

# volumes:
  # postgresql_data:
  #   driver: local
  # sqlite_data:
  #   driver: local
  # vault_data:
  #   driver: local