####################################
# Notes
# Tous les outils doivent etre nomme en entier (exception pour vault),
#   minuscule, sans separation.
# transcendence sera toujours orthographe avec un 'e', pour la version anglaise.
# l'ordre doit etre toujours:
#   - image:
#   - extends:
#   - ports:
#   - depends_on:
#   - volumes:
#   - environnement:
#   - networks:
#       - doitetreuneliste
####################################

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  fastify:
    container_name: fastify
    image: custom-fastify
    build:
      context: ./Backend
      dockerfile: Fastify/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REDIS_URL="redis://redis:6379"
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - redis
      - vault
    volumes:
      - ./Backend/Fastify:/app
      - /app/node_modules   # Préserve les modules installés dans le container
      - ./Data/vault_data:/app/vault/data
      - ./Data/sqlite_data:/app/Data/db

  nginx:
    container_name: nginx
    # image: nginx:latest     # pour ne pas a avoir besoin de Dockerfile
    build:
      context: ./Security
      dockerfile: Nginx/Dockerfile
    ports:
      - "8080:80"           #80:80 necessite des privilege
    depends_on:
      - fastify
    volumes:
      # - ./Security/Nginx/conf.d:/etc/nginx/conf.d # ro mean read-only
      # - ./Security/Nginx/nginx.conf:/etc/nginx/nginx.conf # ro mean read-only
      - ./Security/Nginx/modsecurity:/etc/nginx/modsecurity
      - ./Frontend/public:/usr/share/nginx/html:ro
      - ./Frontend/utils:/usr/share/nginx/utils:ro
      - ./Frontend3d/public:/usr/share/nginx/3d:ro



  # Devops (Grafana + Prometheus + ELK)
  # grafana:
  #   extends:
  #     file: Devops/docker-compose.yml
  #     service: grafana
  #   networks:
  #     - transcendence-network


  # Sécurité (Vault + SonarQube + Modsecurity)
  vault:
    image: custom-vault
    container_name: vault
    build:
      context: ./Security/Vault
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root
    volumes:
      - ./Data/vault_data:/vault/data
      - ./Security/Vault/scripts:/vault/scripts
      # - ./Security/Vault/vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    # entrypoint: "vault server -dev -dev-listen-address=0.0.0.0:8200"

# networks:
#   transcendence-network:
#      driver: bridge

# volumes:
  # postgresql_data:
  #   driver: local
  # sqlite_data:
  #   driver: local
  # vault_data:
  #   driver: local