####################################
# Notes
# Tous les outils doivent etre nomme en entier (exception pour vault),
#   minuscule, sans separation.
# transcendence sera toujours orthographe avec un 'e', pour la version anglaise.
# l'ordre doit etre toujours:
#   - image:
#   - extends:
#   - ports:
#   - depends_on:
#   - volumes:
#   - environnement:
#   - networks:
#       - doitetreuneliste
####################################

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  fastify:
    build:
      context: ./Backend
      dockerfile: Fastify/Dockerfile
    # extends:
    #   file: Backend/docker-compose.yml
    #   service: fastify
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./Backend/Fastify:/app
      - /app/node_modules   # Préserve les modules installés dans le container
    # networks:
    #   - transcendence-network

  nginx:
    # extends:
    #   file: Backend/docker-compose.yml
    #   service: nginx
    image: nginx:latest     # pour ne pas a avoir besoin de Dockerfile
    ports:
      - "8080:80"           #80:80 necessite des privilege
    depends_on:
      - fastify
    volumes:
      - ./Backend/Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # ro mean read-only
      - ./Frontend/public:/usr/share/nginx/html:ro
      - ./Frontend/utils:/usr/share/nginx/utils:ro
      # - ./Frontend3d/public:/usr/share/nginx/3d:ro
    # networks:
    #   - transcendence-network

  # Devops (Grafana + Prometheus + ELK) - À activer plus tard
  # grafana:
  #   extends:
  #     file: Devops/docker-compose.yml
  #     service: grafana
  #   networks:
  #     - transcendence-network

  # Sécurité (Vault + SonarQube) - À activer plus tard
  # vault:
  #   extends:
  #     file: Security/docker-compose.yml
  #     service: vault
  #   networks:
  #     - transcendence-network

# networks:
#   transcendence-network:
#      driver: bridge

# volumes:
  # postgresql_data:
  #   driver: local
  # sqlite_data:
  #   driver: local
  # vault_data:
  #   driver: local