####################################
# Notes
# Tous les outils doivent etre nomme en entier (exception pour vault),
#   minuscule, sans separation.
# transcendence sera toujours orthographe avec un 'e', pour la version anglaise.
# l'ordre doit etre toujours:
#   - image:
#   - extends:
#   - ports:
#   - depends_on:
#   - volumes:
#   - environnement:
#   - networks:
#       - doitetreuneliste
####################################

services:
  fastify:
    extends:
      file: MiniBackend/docker-compose.yml
      service: fastify
    volumes:
      - ./MiniBackend/Fastify:/app
      - /app/node_modules   # Préserve les modules installés dans le container
    # networks:
    #   - transcendence-network

  nginx:
    extends:
      file: MiniBackend/docker-compose.yml
      service: nginx
    volumes:
      - ./MiniBackend/Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # ro mean read-only
      - ./MiniBackend/MiniFrontEnd/public:/usr/share/nginx/html:ro
      - ./MiniBackend/MiniFrontEnd/utils:/usr/share/nginx/utils:ro
    # networks:
    #   - transcendence-network

  # Devops (Grafana + Prometheus + ELK) - À activer plus tard
  # grafana:
  #   extends:
  #     file: Devops/docker-compose.yml
  #     service: grafana
  #   networks:
  #     - transcendence-network

  # Sécurité (Vault + SonarQube) - À activer plus tard
  # vault:
  #   extends:
  #     file: Security/docker-compose.yml
  #     service: vault
  #   networks:
  #     - transcendence-network

# networks:
#   transcendence-network:
#      driver: bridge

# volumes:
  # postgresql_data:
  #   driver: local
  # sqlite_data:
  #   driver: local
  # vault_data:
  #   driver: local