version: "3.8"

services:
  fastify:
    build:
      context: .
      dockerfile: Fastify/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./Fastify:/Fastify
    # networks:
    #   - transcendence-network

  nginx:
    image: nginx:latest # pour ne pas a avoir besoin de Dockerfile
    ports:
      - "8080:80" #80:80 necessite des privilege
    volumes:
      - ./Nginx/default.conf:/etc/nginx/default.conf:ro # ro mean read-only
    depends_on:
      - fastify
    # networks:
    #   - transcendence-network


# networks:
#   transcendence-network:
#      driver: bridge