services:
  fastify:
    build:
      context: .
      dockerfile: Fastify/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest     # pour ne pas a avoir besoin de Dockerfile
    ports:
      - "8080:80"           #80:80 necessite des privilege
    depends_on:
      - fastify