
services:
  fastify:
    build:
      context: .
      dockerfile: Fastify/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./Fastify:/app
      - /app/node_modules   # Préserve les modules installés dans le container
      # - ./MiniFrontEnd/public:/app/public #tmp
      # - ./MiniFrontEnd/utils:/app/utils #tmp
    # networks:
    #   - transcendence-network

  nginx:
    image: nginx:latest     # pour ne pas a avoir besoin de Dockerfile
    ports:
      - "8080:80"           #80:80 necessite des privilege
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # ro mean read-only
      - ./MiniFrontEnd/public:/usr/share/nginx/html:ro
      - ./MiniFrontEnd/utils:/usr/share/nginx/utils:ro
    depends_on:
      - fastify
    # networks:
    #   - transcendence-network


# networks:
#   transcendence-network:
#      driver: bridge